### ISSUE TITLE
 Crash Report 1.5.25rc1

### ISSUE THREAD

**Issue by Xalis708** [Thutmose/PokecubeLocalization#2]
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 11/09/15 7:12 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
    at net.minecraft.block.BlockFlower.func_149666_a(SourceFile:73)
    at net.minecraft.item.ItemBlock.func_150895_a(ItemBlock.java:181)
    at cofh.thermaldynamics.item.ItemCover.createCoverList(ItemCover.java:106)
    at cofh.thermaldynamics.item.ItemCover.getCoverList(ItemCover.java:123)
    at cofh.thermaldynamics.gui.TDCreativeTabCovers.updateIcon(TDCreativeTabCovers.java:52)
    at cofh.thermaldynamics.gui.TDCreativeTabCovers.func_151244_d(TDCreativeTabCovers.java:29)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147051_a(GuiContainerCreative.java:928)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:760)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1358)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.block.BlockFlower.func_149666_a(SourceFile:73)
    at net.minecraft.item.ItemBlock.func_150895_a(ItemBlock.java:181)
    at cofh.thermaldynamics.item.ItemCover.createCoverList(ItemCover.java:106)
    at cofh.thermaldynamics.item.ItemCover.getCoverList(ItemCover.java:123)
    at cofh.thermaldynamics.gui.TDCreativeTabCovers.updateIcon(TDCreativeTabCovers.java:52)
    at cofh.thermaldynamics.gui.TDCreativeTabCovers.func_151244_d(TDCreativeTabCovers.java:29)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147051_a(GuiContainerCreative.java:928)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:760)
    at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78)
    at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)

-- Screen render details --
Details:
    Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
    Mouse location: Scaled: (327, 21). Absolute: (1311, 948)
    Screen size: Scaled: (480, 259). Absolute: (1920, 1033). Scale factor of 4

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [GCEntityClientPlayerMP['Rainer708'/66, l='MpServer', x=24.68, y=114.19, z=382.76]]
    Chunk stats: MultiplayerChunkCache: 161, 497
    Level seed: 0
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (180,87,244), Chunk: (at 4,5,4 in 11,15; contains blocks 176,0,240 to 191,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 17430 game time, 2451 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 69 total; [GenericPokemob41['Zubat'/25093, l='MpServer', x=51.59, y=11.35, z=353.88], EntityVillager['Villager'/7, l='MpServer', x=16.28, y=74.00, z=320.31], EntityVillager['Villager'/9, l='MpServer', x=25.69, y=73.00, z=319.31], EntityVillager['Villager'/10, l='MpServer', x=33.94, y=76.50, z=335.50], EntityItemFrame['entity.ItemFrame.name'/11, l='MpServer', x=42.50, y=80.50, z=339.06], EntityItemFrame['entity.ItemFrame.name'/12, l='MpServer', x=29.50, y=80.50, z=341.94], EntityVillager['Villager'/13, l='MpServer', x=32.69, y=77.00, z=343.53], EntityVillager['Villager'/15, l='MpServer', x=29.50, y=78.00, z=349.69], EntityVillager['Villager'/17, l='MpServer', x=45.31, y=70.00, z=309.69], EntityVillager['Villager'/18, l='MpServer', x=36.75, y=72.00, z=314.50], EntityVillager['Villager'/19, l='MpServer', x=44.66, y=70.00, z=313.44], EntityVillager['Villager'/20, l='MpServer', x=53.88, y=77.00, z=325.69], EntityItemFrame['entity.ItemFrame.name'/21, l='MpServer', x=42.50, y=80.50, z=339.06], EntityVillager['Villager'/22, l='MpServer', x=42.03, y=77.00, z=336.91], EntityVillager['Villager'/23, l='MpServer', x=30.41, y=77.00, z=343.69], GenericPokemob41['Zubat'/24110, l='MpServer', x=4.28, y=77.00, z=319.63], GenericPokemob41['Zubat'/24118, l='MpServer', x=23.69, y=74.06, z=319.84], GenericPokemob41['Zubat'/24124, l='MpServer', x=11.47, y=-13.57, z=321.53], GCEntityClientPlayerMP['Rainer708'/66, l='MpServer', x=191.97, y=83.62, z=220.73], GenericPokemob235['Smeargle'/22606, l='MpServer', x=31.47, y=77.00, z=328.53], GenericPokemob519['Pidove'/20632, l='MpServer', x=46.31, y=86.34, z=319.69], GenericPokemob21['Spearow'/25256, l='MpServer', x=20.25, y=95.09, z=383.75], GenericPokemob21['Spearow'/25258, l='MpServer', x=18.19, y=72.16, z=401.94], GenericPokemob52['Meowth'/20666, l='MpServer', x=49.44, y=69.00, z=305.31], GenericPokemob74['Geodude'/25804, l='MpServer', x=17.56, y=97.00, z=395.41], GenericPokemob519['Pidove'/22742, l='MpServer', x=39.56, y=70.84, z=340.25], GenericPokemob519['Pidove'/22744, l='MpServer', x=58.06, y=71.03, z=317.88], GenericPokemob519['Pidove'/22746, l='MpServer', x=50.69, y=70.69, z=311.53], GCEntityClientPlayerMP['Rainer708'/66, l='MpServer', x=24.68, y=114.19, z=382.76], EntityVillager['Villager'/20209, l='MpServer', x=26.53, y=78.00, z=349.06], EntityVillager['Villager'/20210, l='MpServer', x=27.29, y=86.00, z=365.80], GCEntityClientPlayerMP['Rainer708'/66, l='MpServer', x=186.30, y=74.78, z=245.93], EntityItem['item.tile.mushroom'/24829, l='MpServer', x=-36.16, y=43.13, z=367.38], EntityItem['item.tile.flower1.dandelion'/26402, l='MpServer', x=17.41, y=64.13, z=445.03], EntityItem['item.tile.flower2.poppy'/26409, l='MpServer', x=79.72, y=78.13, z=380.53], EntityItem['item.tile.flower2.poppy'/26410, l='MpServer', x=71.19, y=66.13, z=407.16], GenericPokemob21['Spearow'/26411, l='MpServer', x=50.34, y=99.93, z=372.83], GenericPokemob41['Zubat'/26423, l='MpServer', x=35.63, y=-3.88, z=357.47], EntityItem['item.item.seeds'/26428, l='MpServer', x=51.72, y=65.63, z=428.88], EntityItem['item.item.seeds'/26430, l='MpServer', x=49.97, y=75.38, z=424.69], GenericPokemob41['Zubat'/22932, l='MpServer', x=24.69, y=74.66, z=319.69], EntityTrainer['Super Nerd Daniel'/21403, l='MpServer', x=46.09, y=75.00, z=315.56], GenericPokemob41['Zubat'/22940, l='MpServer', x=32.38, y=1.18, z=319.59], GenericPokemob41['Zubat'/22946, l='MpServer', x=11.47, y=-14.05, z=315.38], GenericPokemob41['Zubat'/22950, l='MpServer', x=51.28, y=51.42, z=306.38], GenericPokemob41['Zubat'/22954, l='MpServer', x=35.97, y=-12.76, z=328.25], GenericPokemob280['Ralts'/21421, l='MpServer', x=60.47, y=71.00, z=317.97], GenericPokemob41['Zubat'/21425, l='MpServer', x=80.59, y=75.41, z=314.25], GenericPokemob41['Zubat'/22962, l='MpServer', x=43.53, y=25.31, z=317.38], GenericPokemob41['Zubat'/21429, l='MpServer', x=73.75, y=66.73, z=320.22], GenericPokemob41['Zubat'/21432, l='MpServer', x=70.22, y=74.00, z=314.75], GenericPokemob41['Zubat'/22972, l='MpServer', x=19.53, y=11.00, z=357.41], GenericPokemob41['Zubat'/21437, l='MpServer', x=79.28, y=66.78, z=315.56], GenericPokemob41['Zubat'/21443, l='MpServer', x=86.38, y=68.78, z=323.31], GenericPokemob41['Zubat'/21447, l='MpServer', x=79.31, y=70.78, z=308.19], GenericPokemob41['Zubat'/22984, l='MpServer', x=26.47, y=11.00, z=317.47], EntityItem['item.tile.flower1.dandelion'/26574, l='MpServer', x=14.81, y=63.13, z=440.28], GenericPokemob41['Zubat'/21455, l='MpServer', x=81.69, y=40.80, z=318.19], GenericPokemob41['Zubat'/21457, l='MpServer', x=83.34, y=75.00, z=305.44], GenericPokemob41['Zubat'/21459, l='MpServer', x=75.34, y=44.14, z=322.09], GenericPokemob41['Zubat'/25047, l='MpServer', x=37.34, y=2.63, z=345.47], GenericPokemob41['Zubat'/21467, l='MpServer', x=89.19, y=79.53, z=318.81], GenericPokemob41['Zubat'/25053, l='MpServer', x=63.53, y=8.53, z=339.63], GenericPokemob41['Zubat'/21475, l='MpServer', x=83.47, y=32.41, z=332.88], GenericPokemob519['Pidove'/24043, l='MpServer', x=27.47, y=76.44, z=361.16], GenericPokemob41['Zubat'/21483, l='MpServer', x=66.41, y=75.25, z=308.41], GenericPokemob519['Pidove'/24045, l='MpServer', x=29.06, y=83.09, z=367.25], GenericPokemob519['Pidove'/24047, l='MpServer', x=16.31, y=93.22, z=359.69], GenericPokemob144['Articuno'/26100, l='MpServer', x=25.59, y=113.72, z=385.28]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows Vista (x86) version 6.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
    Memory: 28937032 bytes (27 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1481 Optifine OptiFine_1.7.10_HD_U_C1 58 mods loaded, 58 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1481-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1481} [Minecraft Forge](forge-1.7.10-10.13.4.1481-1.7.10.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.7.46} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   Micdoodlecore{} [Micdoodle8 Core](minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.5.111} [Not Enough Items](NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
    UCHIJAAAA   OpenModsCore{0.8} [OpenModsCore](minecraft.jar) 
    UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJAAAA   debug{1.0} [debug](denseores-1.6.2.jar) 
    UCHIJAAAA   AncientWarfare{2.4.112-beta-MC1.7.10} [Ancient Warfare Core](ancientwarfare-2.4.112-beta-MC1.7.10-FULL.jar) 
    UCHIJAAAA   CoFHCore{1.7.10R3.0.4B1} [CoFH Core](CoFHCore-[1.7.10]3.0.4B1-308.jar) 
    UCHIJAAAA   AncientWarfareAutomation{2.4.112-beta-MC1.7.10} [Ancient Warfare Automation](ancientwarfare-2.4.112-beta-MC1.7.10-FULL.jar) 
    UCHIJAAAA   AncientWarfareNEIPlugin{2.4.112-beta-MC1.7.10} [Ancient Warfare NEI Plugin](ancientwarfare-2.4.112-beta-MC1.7.10-FULL.jar) 
    UCHIJAAAA   AncientWarfareNpc{2.4.112-beta-MC1.7.10} [Ancient Warfare NPCs](ancientwarfare-2.4.112-beta-MC1.7.10-FULL.jar) 
    UCHIJAAAA   AncientWarfareStructure{2.4.112-beta-MC1.7.10} [Ancient Warfare Structures](ancientwarfare-2.4.112-beta-MC1.7.10-FULL.jar) 
    UCHIJAAAA   antiqueatlas{4.2.6-1.7.10} [Antique Atlas](antiqueatlas-4.2.6-1.7.10.jar) 
    UCHIJAAAA   BiblioCraft{1.11.0} [BiblioCraft](BiblioCraft[v1.11.0][MC1.7.10].jar) 
    UCHIJAAAA   DamageIndicatorsMod{3.2.3} [Damage Indicators](DamageIndicatorsMod-3.2.3.jar) 
    UCHIJAAAA   DynamicLights{1.3.8} [Dynamic Lights](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAA   ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   GalacticraftCore{3.0.12} [Galacticraft Core](GalacticraftCore-1.7-3.0.12.357.jar) 
    UCHIJAAAA   GalacticraftMars{3.0.12} [Galacticraft Planets](Galacticraft-Planets-1.7-3.0.12.357.jar) 
    UCHIJAAAA   GardenContainers{1.7.10-1.6.8} [Garden Containers](GardenStuff-1.7.10-1.6.8.jar) 
    UCHIJAAAA   GardenCore{1.7.10-1.6.8} [Garden Core](GardenStuff-1.7.10-1.6.8.jar) 
    UCHIJAAAA   GardenStuff{1.7.10-1.6.8} [Garden Stuff](GardenStuff-1.7.10-1.6.8.jar) 
    UCHIJAAAA   GardenTrees{1.7.10-1.6.8} [Garden Trees](GardenStuff-1.7.10-1.6.8.jar) 
    UCHIJAAAA   inventorytweaks{1.58-147-645ca10} [Inventory Tweaks](InventoryTweaks-1.58-147.jar) 
    UCHIJAAAA   JABBA{1.2.1} [JABBA](Jabba-1.2.1a_1.7.10.jar) 
    UCHIJAAAA   movillages{1.2.1} [Mo' Villages](MoVillages-1.3.1.jar) 
    UCHIJAAAA   AS_MultiMine{1.4.3} [Multi Mine](MultiMine-1.7.10.jar) 
    UCHIJAAAA   OpenMods{0.8} [OpenMods](OpenModsLib-1.7.10-0.8.jar) 
    UCHIJAAAA   OpenBlocks{1.4.4} [OpenBlocks](OpenBlocks-1.7.10-1.4.4.jar) 
    UCHIJAAAA   Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJAAAA   pokecube_adventures{0.1.0} [Pokecube Adventures](pokecube-1.5.25rc1.jar) 
    UCHIJAAAA   PokecubeCompat{1.0} [Pokecube Compat](pokecube-1.5.25rc1.jar) 
    UCHIJAAAA   pokecube{1.5.25} [Pokecube](pokecube-1.5.25rc1.jar) 
    UCHIJAAAA   pokecube_generations{7.0.0} [Pokecube Generations](pokecube-1.5.25rc1.jar) 
    UCHIJAAAA   pokecube_lineage{0.9} [Pokecube Lineage](pokecube-1.5.25rc1.jar) 
    UCHIJAAAA   pokecube_ml{0.1.0} [Pokecube Model Loader](pokecube-1.5.25rc1.jar) 
    UCHIJAAAA   pokecube_origin{1.5.25} [Pokecube Origin](pokecube-1.5.25rc1.jar) 
    UCHIJAAAA   pokecube_world{0.0.1} [Thut's WorldGen: Pokecube Edition](pokecube-1.5.25rc1.jar) 
    UCHIJAAAA   ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.0-102.jar) 
    UCHIJAAAA   ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.1.0-161.jar) 
    UCHIJAAAA   ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
    UCHIJAAAA   trashslot{1.0.14} [TrashSlot](trashslot-mc1.7.10-1.0.14.jar) 
    UCHIJAAAA   trophyslots{1.3.0} [Trophy Slots](Trophy Slots-1.7.10-1.3.0-universal.jar) 
    UCHIJAAAA   denseores{1.0} [Dense Ores](denseores-1.6.2.jar) 
    UCHIJAAAA   ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.2.0' Renderer: 'GeForce 8800 GT/PCI/SSE2'
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Class transformer null safety: all safe
    CoFHCore: -[1.7.10]3.0.4B1-308
    ThermalFoundation: -[1.7.10]1.2.0-102
    ThermalDynamics: -[1.7.10]1.1.0-161
    ThermalExpansion: -[1.7.10]4.0.3B1-218
    Stencil buffer state: Function set: GL30, pool: forge, bits: 8
    Launched Version: 1.7.10-Forge10.13.4.1481-1.7.10
    LWJGL: 2.9.1
    OpenGL: GeForce 8800 GT/PCI/SSE2 GL version 3.2.0, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [Pokecube_Resources.zip]
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by Thutmose** [comment]
this ones doesn't give any useful information to link to pokecube, I will close it and work on the later one instead.
