### ISSUE TITLE
Loosing pokemon when I die

### ISSUE THREAD

**Issue by Xalis708** [Thutmose/PokecubeLocalization#3]
I thought I just missed something the first time it happened, but every time I die I seem to loose all but my starter and 1 other all the rest I had on me disappeared without a trace.

Is there is any info I can send to help find out what's going on?. 

Is this the first time this has happened in your mod?

P.S. I really love this mod and hope this issue can be resolved quickly so I can play without fear of loosing pokemon.

**Comment by Xalis708** [comment]
I did a clean restart with just pokecube and nei used master balls in creative caught some, drowned myself and checked the PC... again I lost half, they just disappeared.

**Comment by Thutmose** [comment]
can you give me any details on the game mode/ game rules/ worn items, etc? I have died many times with pokecubes and they always end up in PC for me.  I will check drowning, I don't think I have died that way with them yet.

Edit: fixed

**Comment by Thutmose** [comment]
Fixed this issue, uploaded fix as 1.5.25rc2, once the other bug can be replicated, that fix will go up as rc3, and if no more bugs after that, I will put out a release build of 25.

**Comment by Xalis708** [comment]
Config's Hardmode=true and semiHard=true, pokecubesOnly=false. In survival
with cheat's is where it started, then try'd creative, in creative I
grabbed a full stack of master cube's and started catching anything till I
had about 8 then /gamemode 0 drowned self lost 4, same as before but then I
try'd /kill with the same results of losing poke's, no items were held, no
/gamerule's.

I just re-tested, creative 9 poke's killed by a group of poke's, checked
the pc and only 2 where saved :(
